spring.application.name=backend-Mobimanten

# Conexión a MongoDB (Local)
spring.mongodb.uri=mongodb://localhost:27017/mobimanten_db

# Habilitar la consola de GraphQL para pruebas rápidas
spring.graphql.graphiql.enabled=true

# (Opcional) Ver las consultas de Mongo en la consola de IntelliJ
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
