spring.application.name=backend-Mobimanten
server.port=${PORT:8080}
spring.mongodb.uri=${MONGO_URL:mongodb://mongo:HXBiVSvgNNlZjSmLytbGCvFtiRoeRxLM@yamabiko.proxy.rlwy.net:11075}
spring.mongodb.database=mobimanten_db
spring.graphql.graphiql.enabled=true
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG
google.client.id=${GOOGLE_CLIENT_ID:YOUR_GOOGLE_CLIENT_ID_HERE}
google.client.secret=${GOOGLE_CLIENT_SECRET:YOUR_GOOGLE_CLIENT_SECRET_HERE}
jwt.secret=${JWT_SECRET:497b70744745427b6863776e7a6b736b7a6b736b7a6b736b7a6b736b7a6b736b}
